# Laboratorium 3 : Zaawansowane funkcje w NumPy

## Marcin Ogórkiewicz 120674, grupa 1

### Zadanie 1.	Funkcje agregujące i statystyki
a.	Wygeneruj tablicę 10 x 10 z losowymi wartościami z zakresu od 1 do 100.
b.	Oblicz sumę wszystkich elementów w tablicy.
c.	Oblicz średnią, maksymalną, minimalną wartość oraz odchylenie standardowe dla całej tablicy.
d.	Oblicz średnią dla każdego wiersza i dla każdej kolumny.


In [4]:
import numpy as np

#a.
array10x10 = np.random.uniform(1, 101, (10, 10)) #tablica o wymiarach 3x3x3 wypełniona losowymi liczbami z zakresu 1 - 100
array10x10

array([[99.87201939, 72.06008454, 68.27986813, 53.46519367, 40.45371168,
        92.51322546, 78.4577423 , 88.03932812, 86.66363499, 52.94075267],
       [24.88309227, 48.96326765, 36.72648942, 46.80841313, 71.31347684,
        24.30814719, 48.36195366, 79.78966998, 64.39608837, 51.8550541 ],
       [38.60815686, 56.70841567, 89.35057841,  8.15547306, 55.77683559,
        84.91437395, 81.22679807, 13.06799988, 77.36698766, 90.60998327],
       [57.35520591, 36.4817991 , 51.07072439, 26.80943661, 84.6458232 ,
        99.03262174, 54.57062551, 55.3092614 , 76.39693037, 86.8920992 ],
       [75.7655043 , 50.3888743 , 53.89202192, 20.04372759, 69.20402015,
        79.6276259 , 34.0775795 , 68.97113132, 37.32644045, 42.16741418],
       [98.62947094, 25.19820712, 77.79306209, 27.45238739, 30.77420019,
        42.50603459, 53.04612799, 48.74606799, 31.25714768, 46.87224353],
       [19.67111642,  7.18575271,  7.63439466, 93.67867932, 78.31190105,
        73.85775006, 76.71516367, 48.60235205

In [5]:
#b.
array10x10.sum() #suma elementów tablicy

5590.288933233322

In [6]:
#c.
array10x10.mean() #średnia wartość elementów tablicy

55.90288933233322

In [7]:
array10x10.max() #wartość maksymalna elementów tablicy

99.87201939482215

In [8]:
array10x10.min() #wartość minimalna elementów tablicy

3.260316415968733

In [9]:
array10x10.std() #odchylenie standardowe elementów tablicy

26.639546551044187

In [11]:
#d.
np.mean(array10x10, axis=1) #średnia wartość elementów każdego wiersza

array([73.2745561 , 49.74056526, 59.57856024, 62.85645274, 53.14643396,
       48.22749495, 49.06252357, 47.99438614, 51.8277216 , 63.32019876])

In [12]:
np.mean(array10x10, axis=0) #średnia wartość elementów każdej kolumny

array([63.26662143, 52.37853904, 58.22621388, 42.22337281, 57.15603053,
       58.1096881 , 56.63203772, 49.6830015 , 59.68579699, 61.66759132])

### Zadanie 2.	Broadcasting
a.	Utwórz tablicę 5 x 5 z losowymi liczbami z zakresu od 1 do 10.
b.	Utwórz wektor o długości 5 z wartościami od 10 do 50.
c.	Wykonaj operację dodawania, gdzie każdy wiersz w tablicy zostanie zwiększony o odpowiednią wartość z wektora.


In [13]:
#a.
array5x5 = np.random.uniform(1, 11, (5, 5)) #tablica o wymiarach 3x3x3 wypełniona losowymi liczbami z zakresu 1 - 100
array5x5

array([[ 5.59749558,  2.79101285,  4.18120221,  2.62487318,  6.32502022],
       [ 1.46076356,  9.50757271,  2.84068071,  5.13686423,  3.71611465],
       [ 8.52399895,  4.0645145 , 10.52495671,  1.74213661,  6.28072455],
       [ 7.95170929,  2.60078094,  9.47661559,  6.88327586,  4.77434747],
       [ 2.06267013,  4.69014526, 10.21896332,  5.99156098,  6.14727886]])

In [14]:
#b.
vector5 = np.random.uniform(10, 51, (1, 5)) #tablica o wymiarach 3x3x3 wypełniona losowymi liczbami z zakresu 1 - 100
vector5

array([[13.33884754, 35.76510132, 43.18395679, 38.81610615, 36.6296611 ]])

In [15]:
#c.
np.add(array5x5, vector5) #dodanie wartości vector5 do każdego wiersza array5x5

array([[18.93634312, 38.55611417, 47.365159  , 41.44097932, 42.95468133],
       [14.7996111 , 45.27267403, 46.0246375 , 43.95297038, 40.34577575],
       [21.86284649, 39.82961582, 53.7089135 , 40.55824276, 42.91038565],
       [21.29055683, 38.36588226, 52.66057238, 45.69938201, 41.40400858],
       [15.40151767, 40.45524658, 53.40292011, 44.80766712, 42.77693997]])

### Zadanie 3.	Generowanie losowych danych i analiza danych testowych
a.	Utwórz tablicę 1000 x 3 z losowymi wartościami z rozkładu normalnego (średnia 50, odchylenie standardowe 10).
b.	Oblicz średnią, medianę, odchylenie standardowe dla każdej kolumny (reprezentujących np. trzy różne testy).
c.	Znajdź liczbę wartości powyżej 60 dla każdej kolumny.


In [16]:
#a.
array1000x3_normal = np.random.normal(50, 10, (1000, 3)) #tablica o wymiarach 1000x3 z losowymi wartościami z rozkładu normalnego średnia = 50, odchylenie standardowe = 10
array1000x3_normal

array([[38.39016659, 50.32890479, 53.35170089],
       [45.40006146, 38.25163341, 56.1815359 ],
       [56.02631829, 32.8953105 , 62.95298787],
       ...,
       [50.07896952, 64.49812726, 37.92837708],
       [50.94731706, 34.5994673 , 49.53844045],
       [41.92467559, 52.38285231, 53.86772276]])

In [17]:
#b
np.mean(array1000x3_normal, axis=0) #średnia wartość elementów każdej kolumny

array([50.23915652, 50.39413494, 49.98899682])

In [18]:
np.median(array1000x3_normal, axis=0) #mediana wartości elementów każdej kolumny

array([50.20216306, 50.41205294, 49.5494282 ])

In [19]:
np.std(array1000x3_normal, axis=0) #odchylenie standardowe wartości elementów każdej kolumny

array([10.15066478, 10.03962054, 10.2102202 ])

In [26]:
#c
np.count_nonzero(array1000x3_normal > 60, axis=0) #liczba wartości powyżej 60 dla każdej kolumny

array([174, 169, 168], dtype=int64)

### Zadanie 4.	Zmiana Analiza danych tablicowych
a.	Poniższy kod generuje dane o wynikach testów 20 studentów z 4 przedmiotów.
b.	Oblicz średnią dla każdego przedmiotu oraz dla każdego studenta.
c.	Znajdź studenta z najwyższą średnią i przedmiot, z którego uzyskano najlepszy wynik średni.


In [44]:
#a.
scores = np.random.randint(60, 100, size=(20, 4))
scores

array([[77, 87, 93, 87],
       [79, 82, 97, 80],
       [80, 79, 85, 86],
       [86, 65, 91, 99],
       [84, 69, 75, 77],
       [74, 86, 86, 76],
       [68, 80, 60, 91],
       [71, 84, 73, 73],
       [85, 87, 61, 76],
       [68, 90, 62, 74],
       [69, 72, 77, 61],
       [61, 85, 94, 97],
       [73, 77, 85, 87],
       [99, 85, 97, 87],
       [89, 61, 82, 61],
       [78, 64, 94, 92],
       [96, 61, 97, 73],
       [69, 73, 63, 74],
       [91, 83, 67, 69],
       [62, 81, 79, 84]])

In [45]:
#b.
subject_avg = np.mean(scores, axis=0) #średnia ocen dla każdego przedmiotu
subject_avg

array([77.95, 77.55, 80.9 , 80.2 ])

In [46]:
student_avg = np.mean(scores, axis=1) #średnia ocen dla każdego studenta
student_avg

array([86.  , 84.5 , 82.5 , 85.25, 76.25, 80.5 , 74.75, 75.25, 77.25,
       73.5 , 69.75, 84.25, 80.5 , 92.  , 73.25, 82.  , 81.75, 69.75,
       77.5 , 76.5 ])

In [48]:
best_student_index = np.argmax(student_avg) #szukanie indeksu studenta z najwyższą średnią ocen
best_student_mean = student_avg[best_student_index] #średnia ocen tego studenta
best_student_index, best_student_mean #wyświetlenie indeksu oraz średniej tego studenta

(13, 92.0)

In [50]:
best_subject_index = np.argmax(subject_avg) #szukanie indeksu przedmiotu z najwyższą średnią ocen
best_subject_mean = subject_avg[best_subject_index] #średnia ocen z tego przedmiotu
best_subject_index, best_subject_mean #wyświetlenie indeksu oraz średniej tego przedmiotu

(2, 80.9)

### Wnioski

Podczas laboratorium przećwiczyłem korzystanie z funkcji agregujących, statystycznych, broadcastingu a także generowanie losowych danych przy użyciu biblioteki NumPy.