# Laboratorium 5 : Wprowadzenie do PyTorch i Tensorów

## Marcin Ogórkiewicz 120674, grupa 1

### Zadanie 1: Tworzenie tensorów
1. Stwórz tensor 3x3 zawierający wartości losowe przy użyciu torch.rand.
2. Stwórz tensor jednostkowy 4x4 przy użyciu torch.eye.
3. Stwórz tensor zawierający liczby całkowite od 1 do 9 w formie macierzy 3x3.
4. Zmieniaj kształt tensora z punktu 3 przy użyciu funkcji reshape.

In [39]:
import torch
import numpy as np

#1.
tensor3x3_rand = torch.rand(3, 3) #tensor 3x3 zawierający losowe wartości
tensor3x3_rand

tensor([[0.0455, 0.8478, 0.5486],
        [0.5298, 0.8996, 0.1583],
        [0.7308, 0.5565, 0.7835]])

In [40]:
#2.
tensor4x4_1 = torch.eye(4, 4) #tensor jednostkowy 4x4
tensor4x4_1

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [41]:
#3.
tensor3x3 = torch.arange(1, 10).reshape(3, 3) #stworzenie tensora jednowymiarowego wypełnionego liczbami z zakresu 1 - 9 i zamiana go na tensor dwuwymiarowy 3x3
tensor3x3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
#4.
tensor3x3.reshape(1, 9) #ponowna zamiana na tensor jednowymiarowy

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Zadanie 2: Operacje na tensorach
1. Stwórz dwa tensory o wymiarach 2x2:
a. A = [[1, 2], [3, 4]]
b. B = [[5, 6], [7, 8]]
2. Wykonaj następujące operacje:
a. Dodawanie tensorów.
b. Mnożenie tensorów (element po elemencie).
c. Mnożenie macierzowe.


In [5]:
#1
A = torch.tensor([[1, 2], [3, 4]]) #tensor A
B = torch.tensor([[5, 6], [7, 8]]) #tensor B

In [6]:
#2a. dodawanie tensorów
A+B 

tensor([[ 6,  8],
        [10, 12]])

In [7]:
#b. mnożenie tensorów(element po elemencie)
A*B

tensor([[ 5, 12],
        [21, 32]])

In [8]:
#c. mnożenie macierzowe
torch.matmul(A, B)

tensor([[19, 22],
        [43, 50]])

### Zadanie 3: Indeksowanie i wycinanie
1. Stwórz tensor 4x4 zawierający liczby od 1 do 16.
2. Wykonaj następujące operacje:
a. Wyciągnij cały drugi wiersz.
b. Wyciągnij trzeci element z drugiego wiersza.
c. Wyciągnij podmacierz 2x2 z dolnego prawego rogu.

In [9]:
#1.
tensor4x4 = torch.arange(1, 17).reshape(4,4) #stworzenie tensora jednowymiarowego wypełnionego liczbami z zakresu 1 - 16 i zamiana go na tensor dwuwymiarowy 4x4
tensor4x4

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [10]:
#2.a.
tensor4x4[1, :] #drugi wiersz tensora

tensor([5, 6, 7, 8])

In [11]:
#b.
tensor4x4[1, 2] #trzeci element drugiego wiersza tensora

tensor(7)

In [12]:
#c.
tensor4x4[2:,2:] #podmacierz 2x2 z prawego dolnego rogu tensora

tensor([[11, 12],
        [15, 16]])

### Zadanie 4: Praca z GPU
1. Sprawdź, czy masz dostępne GPU za pomocą torch.cuda.is_available().
2. Stwórz tensor na GPU i wykonaj na nim operacje matematyczne (mnożenie, dzielenie,
dodawanie i potęgowanie).
3. Przenieś tensor z GPU na CPU i wyświetl wynik.


In [13]:
#1.
torch.cuda.is_available() #sprawdzenie, czy gpu jest dostępne

True

In [27]:
#2.
cuda_tensor = torch.randint(1, 11, (10, 10)) #utworzenie tensora na cpu
cuda_tensor

tensor([[ 2,  6,  2,  4,  7,  6,  7,  7,  5,  5],
        [ 3,  6,  9,  5,  1, 10, 10,  7,  8,  6],
        [ 5,  3, 10,  3,  8,  9,  9,  7,  6,  2],
        [10, 10,  1,  7,  7,  5,  1,  3, 10,  3],
        [10,  2,  6,  8,  6, 10,  8,  6,  6,  1],
        [ 7,  7,  5,  2,  7,  8,  5,  6,  2,  1],
        [ 2,  5,  8,  7,  5,  4,  9,  8,  5, 10],
        [ 1,  1,  4,  6,  2,  1,  2,  3,  9,  9],
        [ 7,  9,  3,  8,  7,  5,  9, 10,  8,  9],
        [10,  1,  2,  9,  5,  8,  7,  2,  2,  9]])

In [28]:
cuda_tensor = cuda_tensor.to(torch.device('cuda')) #przeniesienie tensora na gpu

In [29]:
cuda_tensor = cuda_tensor*10 #mnożenie
cuda_tensor

tensor([[ 20,  60,  20,  40,  70,  60,  70,  70,  50,  50],
        [ 30,  60,  90,  50,  10, 100, 100,  70,  80,  60],
        [ 50,  30, 100,  30,  80,  90,  90,  70,  60,  20],
        [100, 100,  10,  70,  70,  50,  10,  30, 100,  30],
        [100,  20,  60,  80,  60, 100,  80,  60,  60,  10],
        [ 70,  70,  50,  20,  70,  80,  50,  60,  20,  10],
        [ 20,  50,  80,  70,  50,  40,  90,  80,  50, 100],
        [ 10,  10,  40,  60,  20,  10,  20,  30,  90,  90],
        [ 70,  90,  30,  80,  70,  50,  90, 100,  80,  90],
        [100,  10,  20,  90,  50,  80,  70,  20,  20,  90]], device='cuda:0')

In [30]:
cuda_tensor = cuda_tensor/2 #dzielenie
cuda_tensor

tensor([[10., 30., 10., 20., 35., 30., 35., 35., 25., 25.],
        [15., 30., 45., 25.,  5., 50., 50., 35., 40., 30.],
        [25., 15., 50., 15., 40., 45., 45., 35., 30., 10.],
        [50., 50.,  5., 35., 35., 25.,  5., 15., 50., 15.],
        [50., 10., 30., 40., 30., 50., 40., 30., 30.,  5.],
        [35., 35., 25., 10., 35., 40., 25., 30., 10.,  5.],
        [10., 25., 40., 35., 25., 20., 45., 40., 25., 50.],
        [ 5.,  5., 20., 30., 10.,  5., 10., 15., 45., 45.],
        [35., 45., 15., 40., 35., 25., 45., 50., 40., 45.],
        [50.,  5., 10., 45., 25., 40., 35., 10., 10., 45.]], device='cuda:0')

In [31]:
cuda_tensor = cuda_tensor+5 #dodawanie
cuda_tensor

tensor([[15., 35., 15., 25., 40., 35., 40., 40., 30., 30.],
        [20., 35., 50., 30., 10., 55., 55., 40., 45., 35.],
        [30., 20., 55., 20., 45., 50., 50., 40., 35., 15.],
        [55., 55., 10., 40., 40., 30., 10., 20., 55., 20.],
        [55., 15., 35., 45., 35., 55., 45., 35., 35., 10.],
        [40., 40., 30., 15., 40., 45., 30., 35., 15., 10.],
        [15., 30., 45., 40., 30., 25., 50., 45., 30., 55.],
        [10., 10., 25., 35., 15., 10., 15., 20., 50., 50.],
        [40., 50., 20., 45., 40., 30., 50., 55., 45., 50.],
        [55., 10., 15., 50., 30., 45., 40., 15., 15., 50.]], device='cuda:0')

In [32]:
cuda_tensor = cuda_tensor**2 #potęgowanie
cuda_tensor

tensor([[ 225., 1225.,  225.,  625., 1600., 1225., 1600., 1600.,  900.,  900.],
        [ 400., 1225., 2500.,  900.,  100., 3025., 3025., 1600., 2025., 1225.],
        [ 900.,  400., 3025.,  400., 2025., 2500., 2500., 1600., 1225.,  225.],
        [3025., 3025.,  100., 1600., 1600.,  900.,  100.,  400., 3025.,  400.],
        [3025.,  225., 1225., 2025., 1225., 3025., 2025., 1225., 1225.,  100.],
        [1600., 1600.,  900.,  225., 1600., 2025.,  900., 1225.,  225.,  100.],
        [ 225.,  900., 2025., 1600.,  900.,  625., 2500., 2025.,  900., 3025.],
        [ 100.,  100.,  625., 1225.,  225.,  100.,  225.,  400., 2500., 2500.],
        [1600., 2500.,  400., 2025., 1600.,  900., 2500., 3025., 2025., 2500.],
        [3025.,  100.,  225., 2500.,  900., 2025., 1600.,  225.,  225., 2500.]],
       device='cuda:0')

In [33]:
#3.
cuda_tensor = cuda_tensor.detach().cpu() #przeniesienie tensora z gpu na cpu
cuda_tensor

tensor([[ 225., 1225.,  225.,  625., 1600., 1225., 1600., 1600.,  900.,  900.],
        [ 400., 1225., 2500.,  900.,  100., 3025., 3025., 1600., 2025., 1225.],
        [ 900.,  400., 3025.,  400., 2025., 2500., 2500., 1600., 1225.,  225.],
        [3025., 3025.,  100., 1600., 1600.,  900.,  100.,  400., 3025.,  400.],
        [3025.,  225., 1225., 2025., 1225., 3025., 2025., 1225., 1225.,  100.],
        [1600., 1600.,  900.,  225., 1600., 2025.,  900., 1225.,  225.,  100.],
        [ 225.,  900., 2025., 1600.,  900.,  625., 2500., 2025.,  900., 3025.],
        [ 100.,  100.,  625., 1225.,  225.,  100.,  225.,  400., 2500., 2500.],
        [1600., 2500.,  400., 2025., 1600.,  900., 2500., 3025., 2025., 2500.],
        [3025.,  100.,  225., 2500.,  900., 2025., 1600.,  225.,  225., 2500.]])

### Zadanie 5: Konwersja między NumPy a PyTorch
1. Stwórz tablicę NumPy zawierającą liczby od 0 do 5.
2. Przekonwertuj ją na tensor PyTorch.
3. Przekonwertuj tensor PyTorch z powrotem na tablicę NumPy.

In [43]:
#1.
numpy_array = np.arange(0, 6) #tablica numpy zawierająca liczby z zakresu 0 - 5
numpy_array

array([0, 1, 2, 3, 4, 5])

In [44]:
#2.
torch_tensor = torch.from_numpy(numpy_array) #konwersja tablicy numpy na tensor torch
torch_tensor

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)

In [45]:
#3.
torch_to_numpy = torch_tensor.numpy() #konwersja tensora torch na tablicę numpy
torch_to_numpy

array([0, 1, 2, 3, 4, 5])

### Wnioski

Podczas laboratorium miałem okazję popracować na tensorach w bibliotece torch. Szczególnie ważnym dla mnie elementem zajęć była praca na GPU, ze względu na bogate zastosowanie tego rozwiązania w uczeniu maszynowym, którym się interesuję.