# Laboratorium 6 : PyTorch - Pakiet Autograd

## Marcin Ogórkiewicz 120674, grupa 1

### Zadanie 1: Podstawowe różniczkowanie

In [10]:
import torch

#1. Utworzenie tensora x z requires_grad=True
x = torch.tensor(5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [11]:
#2. Obliczenie funkcji y
y = x**3 - 4*x**2 + 2*x - 7
y

tensor(28., grad_fn=<SubBackward0>)

In [12]:
#3. Obliczenie gradientu funkcji y względem x
y.backward()
x.grad.item()

37.0

### Zadanie 2: Gradienty dla wielowymiarowych tensorów


In [13]:
#1. Utworzenie tensora x z requires_grad=True
x = torch.tensor([2.0, 3.0], requires_grad=True)

In [14]:
#2. Obliczenie funkcji y
y = x[0]**2 + 3 * x[1]**2 + 2 * x[0] * x[1]
y

tensor(43., grad_fn=<AddBackward0>)

In [15]:
#3. Obliczenie gradientów
y.backward()
x.grad[0].item()

10.0

In [16]:
#c. mnożenie macierzowe
x.grad[1].item()

22.0

### Zadanie 3: Minimalizacja funkcji kwadratowej

In [17]:
#1. Inicjalizacja x z requires_grad=True
x = torch.tensor(10.0, requires_grad=True)
x

tensor(10., requires_grad=True)

In [18]:
#2.
eta = 0.1 #współczynnik uczenia (eta)
#iteracyjna minimalizacja
for i in range(10):
    y = x**2 #obliczanie funkcji y
    y.backward() #obliczanie gradientu
    #aktualizacja x zgodnie z regułą gradientową
    with torch.no_grad():
        x -= eta * x.grad
    x.grad.zero_() #wyzerowanie gradientu dla kolejnej iteracji
    print(f"Iteracja {i+1}: x = {x.item()}, y = {y.item()}") #wyświetlanie wyników dla każdej iteracji


Iteracja 1: x = 8.0, y = 100.0
Iteracja 2: x = 6.400000095367432, y = 64.0
Iteracja 3: x = 5.119999885559082, y = 40.96000289916992
Iteracja 4: x = 4.095999717712402, y = 26.214399337768555
Iteracja 5: x = 3.2767996788024902, y = 16.77721405029297
Iteracja 6: x = 2.6214396953582764, y = 10.73741626739502
Iteracja 7: x = 2.097151756286621, y = 6.871945858001709
Iteracja 8: x = 1.677721381187439, y = 4.398045539855957
Iteracja 9: x = 1.342177152633667, y = 2.814749002456665
Iteracja 10: x = 1.0737416744232178, y = 1.8014395236968994


### Zadanie 4: Zarządzanie gradientami

In [21]:
#1. Utworzenie tensora z requires_grad=True
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [22]:
#2. Obliczenie y = x^3 bez śledzenia gradientów
with torch.no_grad():
    y = x**3
y.item()

27.0

In [23]:
x.requires_grad

True

Gradient dostępny dla x

In [24]:
y.requires_grad

False

Gradient niedostępny dla y

### Zadanie 5: Obliczanie gradientów dla sieci neuronowej

In [35]:
#1. Utworzenie losowego tensora x z requires_grad=True
x = torch.rand(1, 3, requires_grad=True)
x

tensor([[0.1920, 0.5575, 0.8163]], requires_grad=True)

In [36]:
#2.
w = torch.tensor([2.0, -3.0, 1.0], requires_grad=True) #tensor w
w

tensor([ 2., -3.,  1.], requires_grad=True)

In [37]:
b = torch.tensor(5.0, requires_grad=True) #tensor b
b

tensor(5., requires_grad=True)

In [38]:
y = torch.matmul(x, w) + b #obliczenie funkcji liniowej y = wx + b
y.backward()
y.item()

4.527758598327637

In [41]:
w.grad

tensor([0.1920, 0.5575, 0.8163])

In [43]:
b.grad

tensor(1.)

### Wnioski

Podczas laboratorium zaznajomiłem się z pakietem Autograd z biblioteki Pytorch. Dzięki temu nauczyłem się obliczać gradienty z pomocą Pythona.