# Laboratorium 2 : Wprowadzenie do NumPy – praca na tensorach

## Marcin Ogórkiewicz 120674, grupa 1

### Zadanie 1.	Tworzenie tensorów
a.	Stwórz jednowymiarowy tensor o 10 elementach (od 0 do 9) za pomocą funkcji np.arange().
b.	Stwórz dwuwymiarowy tensor (macierz) o wymiarach 3x3 wypełniony jedynkami za pomocą funkcji np.ones().
c.	Stwórz trójwymiarowy tensor o wymiarach 2x3x4, gdzie wszystkie wartości to losowe liczby zmiennoprzecinkowe z przedziału od 0 do 1 (użyj np.random.rand()).


In [2]:
import numpy as np

#a.
tensor1d = np.arange(0, 10) #tensor jednowymiarowy zawierający 10 liczb 0 - 9
tensor1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#b.
tensor2d = np.ones((3, 3)) #tensor dwuwymiarowy wypełniony jedynkami
tensor2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
tensor3d = np.random.rand(2, 3, 4) #tensor trójwymiarowy, o wymiarach 2x3x4 wypełniony wartościami zmiennoprzecinkowymi z zakresu 0 - 1 
tensor3d

array([[[0.63979379, 0.20574346, 0.89281398, 0.3615525 ],
        [0.50712184, 0.06025183, 0.14227001, 0.74269664],
        [0.46914357, 0.72835809, 0.6737257 , 0.3041879 ]],

       [[0.32690085, 0.62993059, 0.35390998, 0.82228861],
        [0.66779764, 0.92710435, 0.38962931, 0.63257208],
        [0.54836179, 0.02749633, 0.19730477, 0.11638086]]])

### Zadanie 2.	Podstawowe operacje na tensorach
a.	Utwórz tensor A o wymiarach 3x3, składający się z losowych liczb całkowitych od 1 do 10 (użyj np.random.randint()).
b.	Oblicz sumę wszystkich elementów tensora A.
c.	Znajdź maksymalną i minimalną wartość w tensorze A.


In [13]:
#a.
tensorA  = np.random.randint(1, 11, (3, 3)) #tensor o wymiarach 3x3 wypełniony liczbami całkowitymi z zakresu 1 - 10
tensorA

array([[6, 6, 8],
       [9, 9, 1],
       [8, 8, 3]])

In [14]:
#b.
np.sum(tensorA) #suma wartości tensora

58

In [15]:
#c.
tensorA.max() #największa wartość w tensorze

9

In [16]:
tensorA.min() #najmniejsza wartość w tensorze

1

### Zadanie 3.	Operacje arytmetyczne na tensorach
a.	Stwórz dwa tensory jednowymiarowe B i C o 5 elementach każdy (losowe liczby od 0 do 10).
b.	Wykonaj operacje:
i.	Dodawanie: B + C
ii.	Mnożenie: B * C
iii.	Potęgowanie: B ** 2


In [18]:
#a.
tensorB  = np.random.randint(0, 11, (1, 5)) #tensor jednowymiarowy zawierający 5 liczb całkowitych z zakresu 0 - 10
tensorB

array([[5, 8, 9, 4, 1]])

In [19]:
tensorC  = np.random.randint(0, 11, (1, 5)) #tensor jednowymiarowy zawierający 5 liczb całkowitych z zakresu 0 - 10
tensorC

array([[ 0,  8, 10,  8,  0]])

In [21]:
#b.
#i
np.add(tensorB, tensorC) #suma tensorów przy użyciu funkcji np.add()

array([[ 5, 16, 19, 12,  1]])

In [22]:
#ii
np.multiply(tensorB, tensorC) #iloczyn tensorów przy użyciu funkcji np.multiply()

array([[ 0, 64, 90, 32,  0]])

In [23]:
#iii
np.power(tensorB, 2) #tensorB podniesiony do potęgi drugiej przy użyciu funkcji np.power()

array([[25, 64, 81, 16,  1]], dtype=int32)

### Zadanie 4.	Zmiana wymiarów tensora
a.	Stwórz tensor D o wymiarach 3x4 z losowych liczb całkowitych od 1 do 20.
b.	Zmień kształt (reshape) tensora D tak, aby miał wymiary 2x6.
c.	Wyjaśnij, czy zmiana wymiarów tensora zmieniła jego dane.


In [24]:
#a.
tensorD  = np.random.randint(1, 21, (3, 4)) #tensor o wymiarach 3x4 wypełniony liczbami całkowitymi z zakresu 1 - 20
tensorD

array([[18, 20, 18,  2],
       [16, 18, 20,  5],
       [19, 18, 17,  1]])

In [25]:
#b.
tensorD.reshape(2,6) #zmiana wymiarów tensoraD na 2x6

array([[18, 20, 18,  2, 16, 18],
       [20,  5, 19, 18, 17,  1]])

c. Zmiana wymiarów tensora za pomocą reshape nie zmienia danych. Operacja reshape reorganizuje elementy w pamięci, ale wartości pozostają takie same, jedynie ich struktura ulega zmianie.

### Zadanie 5.	Operacje na wymiarach tensora 
a.	Stwórz tensor E o wymiarach 3x3x3 z losowych liczb od 1 do 5.
b.	Oblicz sumę elementów wzdłuż:
i.	Pierwszego wymiaru.
ii.	Drugiego wymiaru.
iii.	Trzeciego wymiaru.


In [43]:
#a.
tensorE = np.random.uniform(1, 6, (3, 3, 3)) #tensor o wymiarach 3x3x3 wypełniony losowymi liczbami z zakresu 1 - 5
tensorE

array([[[2.24075699, 3.78674694, 1.74597504],
        [1.48756765, 1.58842525, 1.25273697],
        [2.07099454, 2.88516972, 2.16241244]],

       [[2.78192659, 5.34842749, 2.74679797],
        [5.6886688 , 1.27846572, 1.90466917],
        [1.93645626, 3.38322879, 3.93244466]],

       [[3.67373885, 4.98110893, 2.75485401],
        [1.44385023, 2.99385583, 2.30627067],
        [3.17760814, 4.98608013, 2.94201964]]])

In [44]:
#b.
#i.
np.sum(tensorE, axis=0) #suma elementów tensora wzdłuż pierwszego wymiaru

array([[ 8.69642243, 14.11628336,  7.24762702],
       [ 8.62008668,  5.8607468 ,  5.4636768 ],
       [ 7.18505894, 11.25447864,  9.03687675]])

In [45]:
#ii.
np.sum(tensorE, axis=1) #suma elementów tensora wzdłuż drugiego wymiaru

array([[ 5.79931919,  8.26034191,  5.16112445],
       [10.40705165, 10.010122  ,  8.5839118 ],
       [ 8.29519722, 12.96104489,  8.00314433]])

In [46]:
#iii.
np.sum(tensorE, axis=2) #suma elementów tensora wzdłuż trzeciego wymiaru

array([[ 7.77347897,  4.32872987,  7.11857671],
       [10.87715205,  8.87180369,  9.25212971],
       [11.4097018 ,  6.74397673, 11.10570791]])

### Zadanie 6.	Transpozycja tensora
a.	Stwórz macierz F o wymiarach 4x3 z losowych liczb całkowitych od 1 do 10.
b.	Znajdź transpozycję macierzy F.
c.	Zweryfikuj, czy transpozycja ponownie zamieniona na transpozycję da macierz równą oryginalnej.

In [37]:
#a.
matrixF  = np.random.randint(1, 11, (4, 3)) #macierz o wymiarach 4x3 zawierająca liczby całkowite z zakresu 1 - 10
matrixF

array([[ 7,  7,  8],
       [ 2, 10,  8],
       [ 7,  4,  8],
       [ 8, 10,  5]])

In [38]:
#b.
transposed_matrixF = matrixF.transpose() #transpozycja macierzy z poprzedniego podpunktu
transposed_matrixF

array([[ 7,  2,  7,  8],
       [ 7, 10,  4, 10],
       [ 8,  8,  8,  5]])

In [39]:
#c.
transposed_matrixF.transpose() #transpozycja transpozycji macierzy z poprzedniego podpunktu

array([[ 7,  7,  8],
       [ 2, 10,  8],
       [ 7,  4,  8],
       [ 8, 10,  5]])

Jak widać powyżej, ponowna transpozycja przywraca macierz do stanu pierwotnego.

### Zadanie 7.	Mnożenie macierzy
a.	Stwórz dwie macierze G i H o wymiarach 2x3 oraz 3x2 (losowe liczby całkowite od 1 do 5).
b.	Wykonaj mnożenie macierzy G i H (użyj np.dot() lub operatora @).
c.	Zweryfikuj wymiary otrzymanego wyniku.


In [40]:
#a.
matrixG  = np.random.randint(1, 5, (2, 3)) #macierz o wymiarach 2x3 zawierająca liczby całkowite z zakresu 1 - 5
matrixG

array([[4, 4, 3],
       [2, 3, 1]])

In [41]:
matrixH = np.random.randint(1, 5, (3, 2)) #macierz o wymiarach 3x2 zawierająca liczby całkowite z zakresu 1 - 5
matrixH

array([[4, 3],
       [2, 4],
       [4, 2]])

In [42]:
#b
np.dot(matrixG, matrixH)

array([[36, 34],
       [18, 20]])

c. Wymiary powyższej macierzy są poprawne, wynik ma format 2x2

### Zadanie 8.	Wybór elementów i wycinanie (slicing) tensora
a.	Stwórz tensor I o wymiarach 5x5, wypełniony liczbami od 1 do 25.
b.	Wybierz i wyświetl środkowy fragment 3x3 z tensora I.
c.	Wybierz pierwszą kolumnę i ostatni wiersz tensora I.


In [48]:
#a.
tensorI = np.random.uniform(1, 26, (5, 5)) #tensor o wymiarach 5x5 wypełniony losowymi liczbami z zakresu 1 - 25
tensorI

array([[17.05153038, 11.67008892,  6.13629689, 15.67102913, 25.65480049],
       [ 8.54623095,  8.06913655,  5.98017703, 13.25618444,  4.40989022],
       [ 2.76068837, 13.46750553,  5.93328534, 14.5234407 ,  4.995371  ],
       [ 6.46863243, 20.84166437, 18.91641842,  3.5434854 ,  4.3133307 ],
       [14.60508561,  9.16646486, 13.05329844, 10.10923694, 18.98228206]])

In [49]:
#b.
tensorI[1:4, 1:4] #środkowy fragment tensora, zaczynający się od drugiej kolumny i drugiego wiersza

array([[ 8.06913655,  5.98017703, 13.25618444],
       [13.46750553,  5.93328534, 14.5234407 ],
       [20.84166437, 18.91641842,  3.5434854 ]])

In [50]:
#c.
tensorI[0, 4] #pierwsza kolumna i ostatni wiersz tensora

25.65480049017515

### Wnioski

W trakcie laboratorium zaznajomiłem się z pracą na tensorach w bibliotece NumPy, co pomoże mi w tworzeniu własnych modeli uczenia maszynowego.